# docker-compose up
version: "3"

services:
  le_portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - var/run/docker.sock:/var/run/docker.sock
      - v_portainer:/data

  # printer:
  #   image: ydkn/cups
  #   restart: always
  #   ports:
  #    - "631:631"
  #backend
  le_flask:
    image: lelarge/le_site:latest
    ports:
      - "5000:5000"
    depends_on:
      - "le_postgres"

  #postgres datenbank
  le_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: le_db
      POSTGRES_USER: tim
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: db
    volumes:
      - v_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  #meine cloud
  le_drive:
    image: nextcloud
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - v_nextcloud:/var/www/html
    links:
      - le_postgres
    environment:
      POSTGRES_DB: le_db
      POSTGRES_USER: tim
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: db
  # #db konfig App
  le_adminer:
    image: adminer
    restart: always
    ports:
      - 9050:9050

  le_pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "LePihole20"
    volumes:
      - v_pihole:/etc/pihole/
      - v_dnsmaq:/etc/dnsmasq.d/

    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  le_traefik:
    image: "traefik"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  v_portainer:
  v_nextcloud:
  v_postgres:
  v_pihole:
  v_dnsmaq:
